package pat2026;

import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

public class AddWorkday extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddWorkday.class.getName());

    // Window works for any parent (a JFrame like ManagerHome, or a JDialog like ViewEditWorkdays)
    public AddWorkday(java.awt.Window parent) {
        super(parent, java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        setupBackground();
    }

    private void setupBackground() {
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 0, 0));
        javax.swing.JLabel background = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/pat2026/public/image_470e50a4.jpg")));
        this.getLayeredPane().add(background, javax.swing.JLayeredPane.FRAME_CONTENT_LAYER);
        background.setBounds(0, 0, this.getWidth(), this.getHeight());
    }

    // Checks the typed code against the real workers in WorkerDetails.txt
    private boolean workerExists(String code) throws IOException {
        GetWorkers fetcher = new GetWorkers();

        if (fetcher.getWorkerData()) {
            Worker[] workers = fetcher.getWorkers();

            for (int i = 0; i < fetcher.getCount(); i++) {
                if (workers[i].getWorkerCode().equalsIgnoreCase(code)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblLunchStart = new javax.swing.JLabel();
        lblTimeStart = new javax.swing.JLabel();
        txtf2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtf1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtf9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtf4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtf3 = new javax.swing.JTextField();
        lblWorkday = new javax.swing.JLabel();
        txtf6 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtf5 = new javax.swing.JTextField();
        txtf8 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtf7 = new javax.swing.JTextField();
        lblEndTime = new javax.swing.JLabel();
        lblLunchEnd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTimeStart1 = new javax.swing.JLabel();
        txtf10 = new javax.swing.JTextField();
        lblTimeStart2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEditStartMonth = new javax.swing.JTextField();
        txtEditStartDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEditStartYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        lblLunchStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLunchStart.setForeground(new java.awt.Color(255, 255, 255));
        lblLunchStart.setText("Start Lunch:");

        lblTimeStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimeStart.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeStart.setText("Start Time:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(":");

        txtf1.addActionListener(this::txtf1ActionPerformed);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Work Type:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Rows done:");

        txtf9.addActionListener(this::txtf9ActionPerformed);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planting", "Harvesting", "Weeding", "Irrigation", "Maintenance" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");

        txtf3.addActionListener(this::txtf3ActionPerformed);

        lblWorkday.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWorkday.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkday.setText("New Workday:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText(":");

        txtf5.addActionListener(this::txtf5ActionPerformed);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(":");

        txtf7.addActionListener(this::txtf7ActionPerformed);

        lblEndTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndTime.setForeground(new java.awt.Color(255, 255, 255));
        lblEndTime.setText("End Time:");

        lblLunchEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLunchEnd.setForeground(new java.awt.Color(255, 255, 255));
        lblLunchEnd.setText("End Lunch:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Add Workday:");

        lblTimeStart1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimeStart1.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeStart1.setText("Date:");

        txtf10.addActionListener(this::txtf10ActionPerformed);

        lblTimeStart2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimeStart2.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeStart2.setText("Worker Code:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");

        txtEditStartMonth.addActionListener(this::txtEditStartMonthActionPerformed);

        txtEditStartDay.addActionListener(this::txtEditStartDayActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");

        txtEditStartYear.addActionListener(this::txtEditStartYearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWorkday, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTimeStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTimeStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtf10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEditStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEditStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEditStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLunchStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLunchEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtf7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel35)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtf8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtf5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel34)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtf6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtf3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel33)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtf4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel29)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtf2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtf9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkday, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeStart2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEditStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeStart1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeStart)
                    .addComponent(txtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLunchStart)
                    .addComponent(txtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLunchEnd)
                    .addComponent(txtf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(txtf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndTime)
                    .addComponent(txtf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txtf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String workerCode = txtf10.getText().trim().toUpperCase();

            if (workerCode.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a worker code.");
                return;
            }

            if (!workerExists(workerCode)) {
                JOptionPane.showMessageDialog(this, "No worker with the code " + workerCode + " exists.");
                return;
            }

            LocalDate date = LocalDate.of(
                    Integer.parseInt(txtEditStartYear.getText().trim()),
                    Integer.parseInt(txtEditStartMonth.getText().trim()),
                    Integer.parseInt(txtEditStartDay.getText().trim()));

            int startHour = Integer.parseInt(txtf1.getText().trim());
            int startMinute = Integer.parseInt(txtf2.getText().trim());
            int lunchStartHour = Integer.parseInt(txtf3.getText().trim());
            int lunchStartMinute = Integer.parseInt(txtf4.getText().trim());
            int lunchEndHour = Integer.parseInt(txtf5.getText().trim());
            int lunchEndMinute = Integer.parseInt(txtf6.getText().trim());
            int endHour = Integer.parseInt(txtf7.getText().trim());
            int endMinute = Integer.parseInt(txtf8.getText().trim());
            int rows = Integer.parseInt(txtf9.getText().trim());

            // LocalTime.of also rejects invalid values (hour 25, minute 70, etc.)
            LocalTime start = LocalTime.of(startHour, startMinute);
            LocalTime lunchStart = LocalTime.of(lunchStartHour, lunchStartMinute);
            LocalTime lunchEnd = LocalTime.of(lunchEndHour, lunchEndMinute);
            LocalTime end = LocalTime.of(endHour, endMinute);

            if (date.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "The date worked cannot be in the future.");
            }

            if (start.isAfter(lunchStart) || lunchStart.isAfter(lunchEnd) || lunchEnd.isAfter(end)
                    || !start.isBefore(end)) {
                JOptionPane.showMessageDialog(this,
                        "The times must be in order: start, lunch start, lunch end, end.");
                return;
            }

            if (rows < 0) {
                JOptionPane.showMessageDialog(this, "Rows done cannot be negative.");
                return;
            }

            String typeOfWork = (String) jComboBox1.getSelectedItem();
            if (typeOfWork == null || typeOfWork.isBlank()) {
                JOptionPane.showMessageDialog(this, "Please choose or enter a work type.");
                return;
            }

            CreateWorkday workday = new CreateWorkday();

            workday.setDate(date);
            workday.setStartHour(startHour);
            workday.setStartMinute(startMinute);
            workday.setLunchStartHour(lunchStartHour);
            workday.setLunchStartMinute(lunchStartMinute);
            workday.setLunchEndHour(lunchEndHour);
            workday.setLunchEndMinute(lunchEndMinute);
            workday.setEndHour(endHour);
            workday.setEndMinute(endMinute);
            workday.setTypeOfWork(typeOfWork.trim());
            workday.setRowsDone(rows);

            workday.logWorkday(workerCode);

            JOptionPane.showMessageDialog(this, "Workday logged successfully for " + workerCode + "!");
            this.dispose(); // closes the dialog

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only in the time and rows fields.");
        } catch (java.time.DateTimeException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid hour (0-23) and minute (0-59).");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving workday: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf1ActionPerformed

    private void txtf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf3ActionPerformed

    private void txtf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf5ActionPerformed

    private void txtf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf7ActionPerformed

    private void txtf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf10ActionPerformed

    private void txtEditStartMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditStartMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditStartMonthActionPerformed

    private void txtEditStartDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditStartDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditStartDayActionPerformed

    private void txtEditStartYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditStartYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditStartYearActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblLunchEnd;
    private javax.swing.JLabel lblLunchStart;
    private javax.swing.JLabel lblTimeStart;
    private javax.swing.JLabel lblTimeStart1;
    private javax.swing.JLabel lblTimeStart2;
    private javax.swing.JLabel lblWorkday;
    private javax.swing.JTextField txtEditStartDay;
    private javax.swing.JTextField txtEditStartMonth;
    private javax.swing.JTextField txtEditStartYear;
    private javax.swing.JTextField txtf1;
    private javax.swing.JTextField txtf10;
    private javax.swing.JTextField txtf2;
    private javax.swing.JTextField txtf3;
    private javax.swing.JTextField txtf4;
    private javax.swing.JTextField txtf5;
    private javax.swing.JTextField txtf6;
    private javax.swing.JTextField txtf7;
    private javax.swing.JTextField txtf8;
    private javax.swing.JTextField txtf9;
    // End of variables declaration//GEN-END:variables
}
