package pat2026;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ManagerHome extends javax.swing.JFrame {

    private Worker[] workers;
    private int workerCount;
    private Worker manager;

    public ManagerHome(Worker manager) {
        initComponents();
        setupBackground();
        DisplayDetails();
        this.manager = manager;
        lblHeader.setText("Welcome " + manager.getName() + "!");
    }

    private void setupBackground() {
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 0, 0));
        javax.swing.JLabel background = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/pat2026/public/image_470e50a4.jpg")));
        this.getLayeredPane().add(background, javax.swing.JLayeredPane.FRAME_CONTENT_LAYER);
        background.setBounds(0, 0, this.getWidth(), this.getHeight());

    }

    private void DisplayDetails() {
        DefaultTableModel model = (DefaultTableModel) tblWorker.getModel();
        model.setRowCount(0); // clears the empty placeholder row from the designer

        try {
            GetWorkers workerFetcher = new GetWorkers();

            if (workerFetcher.getWorkerData()) {
                workers = workerFetcher.getWorkers();
                workerCount = workerFetcher.getCount();

                for (int i = 0; i < workerCount; i++) {
                    Object[] row = {
                        workers[i].getWorkerCode(),
                        workers[i].getName() + " " + workers[i].getSurname(),
                        workers[i].getStatus(),
                        "View / Edit",
                        "View / Edit"
                    };
                    model.addRow(row);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No workers have been captured yet.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Could not load worker records: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        scrlWorker = new javax.swing.JScrollPane();
        tblWorker = new javax.swing.JTable();
        lblHeader = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnAddWorker = new javax.swing.JButton();
        btnAddWorkday = new javax.swing.JButton();

        jButton2.setText("Add Workday");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrlWorker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrlWorkerMouseClicked(evt);
            }
        });

        tblWorker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Worker Code", "Name and Surname", "Status", "View Personal Details", "View Work"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWorkerMouseClicked(evt);
            }
        });
        scrlWorker.setViewportView(tblWorker);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 153, 51));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Welcome, ");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        btnAddWorker.setText("Add Workday");
        btnAddWorker.addActionListener(this::btnAddWorkerActionPerformed);

        btnAddWorkday.setText("Add Worker");
        btnAddWorkday.addActionListener(this::btnAddWorkdayActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(scrlWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnAddWorkday, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrlWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddWorkday, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrlWorkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrlWorkerMouseClicked

    }//GEN-LAST:event_scrlWorkerMouseClicked

    private void tblWorkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWorkerMouseClicked

        int row = tblWorker.rowAtPoint(evt.getPoint());
        int col = tblWorker.columnAtPoint(evt.getPoint());

        if (row < 0) {
            return; // clicked on empty space
        }

        String workerCode = tblWorker.getValueAt(row, 0).toString();

        if (col == 3) {
            btnWorkerDetails(workerCode);
        } else if (col == 4) {
            btnWorkdays(workerCode);
        }
    }

    private void btnWorkerDetails(String workerCode) {
        ViewEditWorkerInfo dialog = new ViewEditWorkerInfo(this, true, workerCode);
        dialog.setVisible(true);
        DisplayDetails(); // refresh after edits
    }

    private void btnWorkdays(String workerCode) {
        ViewEditWorkdays dialog = new ViewEditWorkdays(this, true, workerCode);
        dialog.setVisible(true);
        DisplayDetails();
    }//GEN-LAST:event_tblWorkerMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            LoginPage login = new LoginPage();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkerActionPerformed
        try {
            AddWorker dialog = new AddWorker(this, true);
            dialog.setVisible(true);
            DisplayDetails();
        } catch (IOException ex) {
            System.getLogger(ManagerHome.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnAddWorkerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddWorkdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddWorkdayActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWorkday;
    private javax.swing.JButton btnAddWorker;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scrlWorker;
    private javax.swing.JTable tblWorker;
    // End of variables declaration//GEN-END:variables
}
