package pat2026;

import java.time.Duration;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ViewWork extends javax.swing.JDialog {

    private String workerCode;
    private Workday[] workdays;   // same order as the table rows
    private int workdayCount = 0; // how many rows the table has
    private DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern("HH:mm");

    public ViewWork(java.awt.Frame parent, boolean modal, String workerCode) {
        super(parent, modal);
        initComponents();
        setupBackground();
        this.workerCode = workerCode;
        displayTableDetails();
    }

    private void setupBackground() {
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 0, 0));
        javax.swing.JLabel background = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/pat2026/public/image_470e50a4.jpg")));
        this.getLayeredPane().add(background, javax.swing.JLayeredPane.FRAME_CONTENT_LAYER);
        background.setBounds(0, 0, this.getWidth(), this.getHeight());

    }

    private void displayTableDetails() {
        DefaultTableModel model = (DefaultTableModel) tblViewWork.getModel();
        model.setRowCount(0); // clears the empty placeholder row from the designer

        try {
            GetWorkerWorkdays workdayFetcher = new GetWorkerWorkdays();

            if (workdayFetcher.getWorkdayData(workerCode)) {
                workdays = workdayFetcher.getWorkdays();
                workdayCount = workdayFetcher.getCount();

                for (int i = 0; i < workdayCount; i++) {
                    Object[] row = {
                        workdays[i].getJobID(),
                        workdays[i].getDateWorked().format(dateFormat),
                        workdays[i].getStartTime().format(timeFormat),
                        workdays[i].getLunchStart().format(timeFormat),
                        workdays[i].getLunchEnd().format(timeFormat),
                        workdays[i].getEndTime().format(timeFormat),
                        formatDuration(workdays[i].getHoursWorked()),
                        workdays[i].getTypeOfWork(),
                        workdays[i].getRowsCompleted()
                    };
                    model.addRow(row);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No workdays have been logged yet.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Could not load workday records: " + e.getMessage());
        }
    }

    // Short form for the table, e.g. "6h 0m"
    private String formatDuration(Duration duration) {
        return duration.toHours() + "h " + duration.toMinutesPart() + "m";
    }

    // Long form for the details box, e.g. "6 hour(s) 0 minute(s)"
    private String formatDurationLong(Duration duration) {
        return duration.toHours() + " hour(s) " + duration.toMinutesPart() + " minute(s)";
    }

    // In NetBeans: right-click tblViewWork > Events > Mouse > mouseClicked
    private void tblViewWorkMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblViewWork.getSelectedRow();
        int column = tblViewWork.getSelectedColumn();
        int lastColumn = tblViewWork.getColumnCount() - 1; // "See full Details" is the last column

        if (row >= 0 && column == lastColumn) {
            Workday day = workdays[row];

            String details = "JobID: " + day.getJobID()
                    + "\nDate Worked: " + day.getDateWorked().format(dateFormat)
                    + "\nStart Time: " + day.getStartTime()
                    + "\nEnd Time: " + day.getEndTime()
                    + "\nLunch Start: " + day.getLunchStart()
                    + "\nLunch End: " + day.getLunchEnd()
                    + "\nLunch Duration: " + formatDurationLong(day.getLunchDuration())
                    + "\nHours Worked (excl. lunch): " + formatDurationLong(day.getHoursWorked())
                    + "\nType of Work: " + day.getTypeOfWork()
                    + "\nRows Completed: " + day.getRowsCompleted();

            JOptionPane.showMessageDialog(this, details,
                    "Workday Details", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlViewWork = new javax.swing.JScrollPane();
        tblViewWork = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblViewWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "JobID", "Date", "Time Start", "Lunch Start", "Lunch End", "Time End", "Time worked", "Type of Work", "Rows Complete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlViewWork.setViewportView(tblViewWork);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("View your work:");

        jButton1.setText("Return to Home");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jButton1))
                    .addComponent(scrlViewWork))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addComponent(scrlViewWork, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrlViewWork;
    private javax.swing.JTable tblViewWork;
    // End of variables declaration//GEN-END:variables
}
